name: Tezos Reward Distributor

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update -y
        sudo apt-get install libenchant1c2a -y
        # Requirements for the software
        pip install -r requirements.txt
        # Requirements to deploy the documentation
        pip install sphinx_rtd_theme
        pip install sphinxcontrib.spelling
        pip install --upgrade recommonmark
        # Requirements to run tests
        pip install flake8
        pip install parameterized

    - name: Lint with black and flake8 
      run: |
        # Check with black
        black --check .
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Run main
      run: |
        python main.py

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: docs/
        pre-build-command: mkdir -p docs/build/ && touch docs/build/.nojekyll
        build-command: sphinx-build -b html . build

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build